nmbsite/media/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^NMBMediaKit.pdf/', views.pdf_view, name='pdf-view'),
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^why-ooh/$', views.whyooh, name='whyooh'),
    # url(r'^social-media/$', views.social_media, name='social_media'),
    url(r'^facebook/$', views.facebook, name='facebook'),
    url(r'^instagram/$', views.instagram, name='instagram'),
    url(r'^design-specs/$', views.design_specs, name='design-specs'),
    url(r'^design-specs/NMBTemplate-Adbike.pdf$', views.adbike_pdf, name='adbike_pdf'),
    url(r'^design-specs/NMBTemplate-AerialInflatable.pdf$', views.aerial_inflatables_pdf, name='aerial_inflatables_pdf'),
    url(r'^design-specs/NMBTemplate-DigitalMobileBillboard.pdf$', views.digital_mobile_pdf, name='digital_mobile_pdf'),
    url(r'^design-specs/NMBTemplate-DigitalAdbike.pdf$', views.digital_adbike_pdf, name='digital_adbike_pdf'),
    url(r'^design-specs/NMBTemplate-NMBTemplate-HumanDirectional.pdf$', views.human_directionals_pdf, name='human_directionals_pdf'),
    url(r'^design-specs/NMBTemplate-MobileBillboard.pdf$', views.mobile_billboards_pdf, name='mobile_billboards_pdf'),
    url(r'^design-specs/NMBTemplate-ProjectionMedia.pdf$', views.projection_media_pdf, name='projection_media_pdf'),
    url(r'^design-specs/NMBTemplate-RollerBoard.pdf$', views.roller_boards_pdf, name='roller_boards_pdf'),
    url(r'^design-specs/NMBTemplate-Segway.pdf$', views.segways_pdf, name='segways_pdf'),
    url(r'^design-specs/NMBTemplate-WalkingBillboard.pdf$', views.walking_billboards_pdf, name='walking_billboards_pdf'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^platforms/$', views.media, name='platforms'),
    url(r'^testimonials/', views.testimonials, name='testimonials'),
    url(r'^clients/', views.clients, name='clients'),
    url(r'^adbikes/$', views.adbikes, name='adbikes'),
    url(r'^aerial-inflatables/', views.inflatables, name='aerial-inflatables'),
    # url(r'^wraps/$', views.wraps, name='wraps'),
    url(r'^brand-ambassadors/$', views.ambassadors, name='brand-ambassadors'),
    url(r'^banners/$', views.banners, name='banners'),
    url(r'^digital-adbikes/$', views.digital_adbikes, name='digital-adbikes'),
    url(r'^fence-wraps/$', views.fence_wraps, name='fence-wraps'),
    url(r'^human-directionals/$', views.human_directionals, name='human-directionals'),
    url(r'^mobile-billboards/$', views.mobile_billboards, name='mobile-billboards'),
    url(r'^projection-media/$', views.projection_media, name='projection-media'),
    url(r'^roller-boards/$', views.roller_boards, name='roller-boards'),
    url(r'^sculptures/$', views.sculptures, name='sculptures'),
    url(r'^segways/$', views.segways, name='segways'),
    url(r'^street-graphics/$', views.street_graphics, name='street-graphics'),
    url(r'^walking-billboards/$', views.walking_billboards, name='walking-billboards'),
    url(r'^3D-mobile-billboards/$', views.mobile_billboards_3D, name='3D-mobile-billboards'),
    url(r'^digital-mobile-billboards/$', views.digital_mobile_billboards, name='digital-mobile-billboards'),

]

nmbsite/nmbsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('media.urls', namespace='media')),
]

nmbsite/media/models.py
from django.db import models

# Create your models here.

nmbsite/media/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'style': 'height: 135px;', 'class': 'form-control'}),
    )

    # the new bit we're adding
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Name:"
        self.fields['email'].label = "Email:"
        self.fields['message'].label = "Message:"

nmbsite/media/views.py
from django.shortcuts import render
from . import forms
from django.core.mail import send_mail
from django.contrib import messages

# new imports that go at the top of the file
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template
from django.http import FileResponse, Http404


def pdf_view(request):
    return render(request, 'media/kit.html')


def home(request):
    return render(request, 'media/home.html')


def about(request):
    return render(request, 'media/about.html')


def whyooh(request):
    return render(request, 'media/why_ooh.html')


def facebook(request):
    return render(request, 'media/facebook_video.html')


def instagram(request):
    return render(request, 'media/instagram_video.html')


def design_specs(request):
    return render(request, 'media/design_specs.html')


def adbike_pdf(request):
    return render(request, 'media/design_spec_pdfs/adbike_pdf.html')


def aerial_inflatables_pdf(request):
    return render(request, 'media/design_spec_pdfs/aerial_inflatables_pdf.html')


def digital_mobile_pdf(request):
    return render(request, 'media/design_spec_pdfs/digital_mobile_pdf.html')


def digital_adbike_pdf(request):
    return render(request, 'media/design_spec_pdfs/digital_adbike_pdf.html')


def human_directionals_pdf(request):
    return render(request, 'media/design_spec_pdfs/human_directionals_pdf.html')


def mobile_billboards_pdf(request):
    return render(request, 'media/design_spec_pdfs/mobile_billboards_pdf.html')


def projection_media_pdf(request):
    return render(request, 'media/design_spec_pdfs/projection_media_pdf.html')


def roller_boards_pdf(request):
    return render(request, 'media/design_spec_pdfs/roller_boards_pdf.html')


def segways_pdf(request):
    return render(request, 'media/design_spec_pdfs/segways_pdf.html')


def walking_billboards_pdf(request):
    return render(request, 'media/design_spec_pdfs/walking_billboards_pdf.html')


def contact(request):
    form = forms.ContactForm()
    if request.method == 'POST':
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            send_mail(
                'Message from nmbmedia.com',
                form.cleaned_data['message'],
                '{name} <{email}>'.format(**form.cleaned_data),
                ['frank@nmbmedia.com', 'sales@nmbmedia.com']
            )
            messages.add_message(request, messages.SUCCESS,
                                 'Thanks for your suggestion!')
            return redirect('media:contact')
    return render(request, 'media/contact.html', {'form': form})


def media(request):
    return render(request, 'media/media.html')


def clients(request):
    return render(request, 'media/clients.html')


def testimonials(request):
    return render(request, 'media/testimonials.html')


def adbikes(request):
    return render(request, 'media/platforms/adbikes.html')


def inflatables(request):
    return render(request, 'media/platforms/inflatables.html')


def wraps(request):
    return render(request, 'media/platforms/wraps.html')


def ambassadors(request):
    return render(request, 'media/platforms/ambassadors.html')


def banners(request):
    return render(request, 'media/platforms/banners.html')


def digital_adbikes(request):
    return render(request, 'media/platforms/digital_adbikes.html')


def fence_wraps(request):
    return render(request, 'media/platforms/fence_wraps.html')


def human_directionals(request):
    return render(request, 'media/platforms/human_directionals.html')


def mobile_billboards(request):
    return render(request, 'media/platforms/mobile_billboards.html')


def projection_media(request):
    return render(request, 'media/platforms/projection_media.html')


def roller_boards(request):
    return render(request, 'media/platforms/roller_boards.html')


def sculptures(request):
    return render(request, 'media/platforms/sculptures.html')


def segways(request):
    return render(request, 'media/platforms/segways.html')


def street_graphics(request):
    return render(request, 'media/platforms/street_graphics.html')


def walking_billboards(request):
    return render(request, 'media/platforms/walking_billboards.html')


def mobile_billboards_3D(request):
    return render(request, 'media/platforms/mobile_billboards_3D.html')


def digital_mobile_billboards(request):
    return render(request, 'media/platforms/digital_mobile_billboards.html')

nmbsite/media/templates/media/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="../../static/media/MDB/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="../../static/media/MDB/css/mdb.min.css" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="../../static/media/main.css" rel="stylesheet">
    <script src="../../static/media/scripts/jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="../../static/media/scripts/lander.js" type="text/javascript"></script>
    <script src="../../static/media/scripts/scroll.js" type="text/javascript"></script>
    <title>NMB Media</title>
</head>

    <body>

		<!-- nav -->
    <div class="container-fluid">
		<nav class="navbar navbar-toggleable-md z-depth-0 navbar-light">
			<div class="pb-md-1">
			  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			  </button>
				<span class="navbar-text hidden-lg-up">&nbsp;</span>
			  <div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
				  <li class="nav-item px-2">
					<a class="nav-link" href="{% url 'media:home' %}">Home <span class="sr-only">(current)</span></a></li>
          <li class="nav-item px-2 dropdown"><a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
            <div class="dropdown-menu p-3" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item p-2" href="{% url 'media:about' %}">Our Story</a>
              <a class="dropdown-item p-2" href="{% url 'media:whyooh' %}">Why OOH?</a>
              <a class="dropdown-item p-2" href="{% url 'media:testimonials' %}">Testimonials</a>
              <a class="dropdown-item p-2" href="{% url 'media:clients' %}">Clients</a>
              <a class="dropdown-item p-2" href="{% url 'media:facebook' %}">Facebook Video</a>
              <a class="dropdown-item p-2" href="{% url 'media:instagram' %}">Instagram Video</a>
            </div>
          </li>
          <li class="nav-item px-2 dropdown"><a class="nav-link dropdown-toggle" href="{% url 'media:platforms' %}" id="navbarDropdownMenuLink"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Media</a>
            <div class="dropdown-menu p-3" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item p-2" href="{% url 'media:adbikes' %}">Adbikes</a>
              <a class="dropdown-item p-2" href="{% url 'media:aerial-inflatables' %}">Aerial Inflatables</a>
              <a class="dropdown-item p-2" href="{% url 'media:digital-mobile-billboards' %}">Digital Mobile Billboards</a>
              <a class="dropdown-item p-2" href="{% url 'media:brand-ambassadors' %}">Brand Ambassadors</a>
              <a class="dropdown-item p-2" href="{% url 'media:banners' %}">Building Banners</a>
              <a class="dropdown-item p-2" href="{% url 'media:digital-adbikes' %}">Digital Adbikes</a>
              <a class="dropdown-item p-2" href="{% url 'media:fence-wraps' %}">Fence Wraps</a>
              <a class="dropdown-item p-2" href="{% url 'media:human-directionals' %}">Human Directionals</a>
              <a class="dropdown-item p-2" href="{% url 'media:mobile-billboards' %}">Mobile Billboards</a>
              <a class="dropdown-item p-2" href="{% url 'media:projection-media' %}">Projection Media</a>
              <a class="dropdown-item p-2" href="{% url 'media:roller-boards' %}">Roller Boards</a>
              <a class="dropdown-item p-2" href="{% url 'media:sculptures' %}">Sculptures</a>
              <a class="dropdown-item p-2" href="{% url 'media:segways' %}">Segways</a>
              <a class="dropdown-item p-2" href="{% url 'media:street-graphics' %}">Street Graphics</a>
              <a class="dropdown-item p-2" href="{% url 'media:walking-billboards' %}">Walking Billboards</a>
              <a class="dropdown-item p-2" href="{% url 'media:3D-mobile-billboards' %}">3D Mobile Billboards</a>
            </div>
          </li>
          <li class="nav-item px-2"><a class="nav-link" href="{% url 'media:design-specs' %}">Design Specs</a></li>
				  <li class="nav-item px-2"><a class="nav-link" href="{% url 'media:contact' %}">Contact</a></li>
				</ul>
			  </div>
			</div>
		</nav>
    </div>
		<!-- nav -->

		 <main class="content">
	      {% block content %}
	      {% endblock %}
	    </main>
		<!-- footer -->
        <div class="bg-faded">
            <div class="container-fluid pt-3">
                <div class="row">
                    <div class="media_footer col-md-3 col-sm-5 mx-auto p-4">
                         <h6 class="pb-1">CORPORATE HEADQUARTERS</h6>
                         <h7>National Mobile Billboards, LLC<br />
                         DBA/NMB Media<br />
                         5101 NW 21 Ave.<br />
                         Suite 340<br />
                         Fort Lauderdale, FL 33309</h7>
                         <h6 class="pt-3 pb-1">CONTACT</h6>
                         <h7>(800) 544-3305</h7>
                    </div>
                     <div id="media_footer_links" class="col-md-3 col-sm-5 mx-auto p-4">
                        <h6>LINKS</h6>
                        <nav class="nav navbar-light flex-column ml-0">
                            <a class="nav-link media-link pl-0" href="{% url 'media:home' %}">Home</a>
                            <div class="nav-item dropdown">
                                <a class="nav-link media-link pl-0 dropdown-toggle" data-toggle="dropdown" href="#"
                                   role="button" aria-haspopup="true" aria-expanded="false">About</a>
                                <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{% url 'media:about' %}">Our Story</a>
                                  <a class="dropdown-item" href="{% url 'media:whyooh' %}">Why OOH?</a>
                                  <a class="dropdown-item" href="{% url 'media:testimonials' %}">Testimonials</a>
                                  <a class="dropdown-item" href="{% url 'media:clients' %}">Clients</a>
                                  <a class="dropdown-item" href="{% url 'media:facebook' %}">Facebook Video</a>
                                  <a class="dropdown-item" href="{% url 'media:instagram' %}">Instagram Video</a>
                                </div>
                            </div>
                            <a class="nav-link media-link pl-0" href="{% url 'media:design-specs' %}">Design Specs</a>
                            <a class="nav-link media-link pl-0" href="{% url 'media:contact' %}">Contact</a>
                            <a class="nav-link media-link pl-0" href="{% url 'media:home' %}#media_link">Media Platforms</a>
                            <a class="nav-link media-link pl-0" href="{% url 'media:pdf-view' %}">NMB Media Kit</a>
                            <a class="nav-link media-link pl-0" href="#">Become A Brand Ambassador</a>
                        </nav>
                    </div>
                    <div class="media_footer col-md-3 col-sm-5 mx-auto p-4">
                         <h6>MEDIA PLACEMENT</h6>
                         <h7><a href="mailto:sales@nmbmedia.com">sales@nmbmedia.com</a></h7>
                         <h6 class="pt-3">DESIGN & PRODUCTION</h6>
                         <h7><a href="mailto:design@nmbmedia.com">design@nmbmedia.com</a></h7>
                         <h6 class="pt-3">CAREERS</h6>
                         <h7><a href="mailto:career@nmbmedia.com">career@nmbmedia.com</a></h7>
                    </div>
                    <div id="media_footer_memberships" class="col-md-2 col-sm-5 mx-auto p-4">
                         <h6 class="pb-2">MEMBERS OF</h6>
                        <div class="row">
                          <a href="http://OAAA.org" class="p-3"><img class="img-fluid" src="../../static/media/images/OOH.png" width=150px /></a>
                        </div>
                        <div class="row">
                          <a href="http://geopath.org" class="p-3"><img class="img-fluid" src="../../static/media/images/Geopath.gif" width=150px /></a>
                        </div>
                    </div>
                </div>
                <div class="row ml-sm-4 pl-sm-3 ml-md-2 justify-content-center">
                    <!-- <a href="https://www.facebook.com/promotionsinmotion/" class="px-2"><img width="40" src="../../static/media/images/youtube.png" /></a> -->
                    <a href="https://www.facebook.com/OOHProfessionals/" class="px-4 py-1"><img width="40" src="../../static/media/images/facebook.png" /></a>
                    <a href="https://www.linkedin.com/company/1319249/" class="px-4 py-1"><img width="40" src="../../static/media/images/linkedin.png" /></a>
                    <a href="https://www.instagram.com/oohprofessionals/" class="px-4 py-1"><img width="40" src="../../static/media/images/instagram.png" /></a>
                </div>
                <div id="footer_rights" class="row ml-sm-4 pl-sm-3 ml-md-2 pb-2">
                    <small class="text-sm-center">&copy; 2017 All Rights Reserved</small>
                </div>
            </div>
        </div>
		<!-- /footer -->

        <!-- SCRIPTS -->
        <!-- JQuery -->
        <script type="text/javascript" src="../../static/media/MDB/js/jquery-3.1.1.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="../../static/media/MDB/js/tether.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="../../static/media/MDB/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="../../static/media/MDB/js/mdb.min.js"></script>
        <!-- WOW -->
        <script type="text/javascript" src="../../static/media/MDB/js/wow.js"></script>
	</body>
</html>

nmbsite/media/templates/media/design_spec_pdfs/adbike_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-Adbike.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/aerial_inflatables_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <object data="../../static/media/docs/NMBTemplate-AerialInflatable.pdf"
    type="application/pdf" height="750px" width="100%">
    <p>This browser does not support PDFs. Please download the PDF to view it:
      <a href="../../../static/media/docs/NMBTemplate-AerialInflatable.pdf">Download PDF</a>.</p>
    </object>
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/digital_adbike_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-DigitalAdbike.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/digital_mobile_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-DigitalMobileBillboard.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/human_directionals_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-HumanDirectional.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/mobile_billboards_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-MobileBillboard.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/projection_media_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-ProjectionMedia.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/roller_boards_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-RollerBoard.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/segways_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-Segway.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_spec_pdfs/walking_billboards_pdf.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}
    <embed src="../../static/media/docs/NMBTemplate-WalkingBillboard.pdf" type="application/pdf" height="750px" width="100%">
{% endblock %}

nmbsite/media/templates/media/design_specs.html
{% extends 'media/base.html' %}
{% load static %}

{% block content %}

<div class="media-about-background">
  <div class="container justify-content-center">
      <section class="section my-3">
          <h1 class="display-4 animated fadeInDown media-text p-4 text-center">Design Specification Templates</h1>
          <p class="section-description animated fadeInDown mb-2">Please click on the appropriate link below for your Design Guide.</p>
          <div class="p-1 type-LineString animated fadeInLeft"></div>
          <div class="row justify-content-center pb-2 pt-4">
              <div class="media-platform-card col-3 mx-auto"><a class="media-link" href="{% url 'media:adbike_pdf' %}">
                <div class="card media-card wow fadeInUp m-0">
                  <div class="row mx-auto p-2">
                    <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/AB.jpg" alt="Adbike">
                  </div>
                  <div class="py-1 px-2 text-center">
                    <h4 class="card-title media-card-title m-0">Adbikes</h4>
                  </div>
                </div></a>
              </div>

              <div class="media-platform-card col-3"><a class="media-link" href="{% url 'media:aerial_inflatables_pdf' %}">
                <div class="card media-card wow fadeInUp">
                    <div class="row mx-auto p-2">
                        <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/infl.jpg" alt="Aerial Inflatable">
                    </div>
                    <div class="py-1 px-2 text-center">
                        <h4 class="card-title media-card-title m-0">Aerial Inflatables</h4>
                    </div>
                </div></a>
              </div>

              <div class="media-platform-card col-3"><a class="media-link" href="{% url 'media:digital_mobile_pdf' %}">
                <div class="card media-card wow fadeInUp">
                  <div class="row mx-auto p-2">
                    <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/DMB.jpg" alt="Digital Mobile Billboards">
                  </div>
                  <div class="py-1 px-2 text-center">
                    <h4 class="card-title media-card-title m-0">Digital Mobile Billboards</h4>
                  </div>
                </div></a>
              </div>

              <div class="media-platform-card"><a class="media-link" href="{% url 'media:digital_adbike_pdf' %}">
                <div class="card media-card wow fadeInUp">
                  <div class="row mx-auto p-2">
                    <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/DAB.jpg" alt="Digital Adbikes">
                  </div>
                  <div class="py-1 px-2 text-center">
                    <h4 class="card-title media-card-title m-0">Digital Adbikes</h4>
                  </div>
                </div></a>
              </div>

              <div class="media-platform-card"><a class="media-link" href="{% url 'media:human_directionals_pdf' %}">
                <div class="card media-card wow fadeInUp">
                  <div class="row mx-auto p-2">
                    <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/HD.jpg" alt="Human Directionals">
                  </div>
                  <div class="py-1 px-2 text-center">
                    <h4 class="card-title media-card-title m-0">Human Directionals</h4>
                  </div>
                </div></a>
              </div>

              <div class="media-platform-card"><a class="media-link" href="{% url 'media:mobile_billboards_pdf' %}">
                <div class="card media-card wow fadeInUp">
                  <div class="row mx-auto p-2">
                    <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/MB.jpg" alt="Mobile Billboards">
                  </div>
                  <div class="py-1 px-2 text-center">
                      <h4 class="card-title media-card-title m-0">Mobile Billboards</h4>
                  </div>
                </div></a>
              </div>

              <div class="media-platform-card"><a class="media-link" href="{% url 'media:projection_media_pdf' %}">
                <div class="card media-card wow fadeInUp">
                  <div class="row mx-auto p-2">
                    <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/PM.jpg" alt="Projection Media">
                  </div>
                  <div class="py-1 px-2 text-center">
                    <h4 class="card-title media-card-title m-0">Projection Media</h4>
                  </div>
                </div></a>
              </div>

              <div class="media-platform-card"><a class="media-link" href="{% url 'media:roller_boards_pdf' %}">
                <div class="card media-card wow fadeInUp">
                  <div class="row mx-auto p-2">
                    <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/RB.jpg" alt="Roller Boards">
                  </div>
                  <div class="py-1 px-2 text-center">
                    <h4 class="card-title media-card-title m-0">Roller Boards</h4>
                  </div>
                </div></a>
              </div>

              <div class="media-platform-card"><a class="media-link" href="{% url 'media:segways_pdf' %}">
                <div class="card media-card wow fadeInUp">
                  <div class="row mx-auto p-2">
                    <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/SW.jpg" alt="Segways">
                  </div>
                  <div class="py-1 px-2 text-center">
                    <h4 class="card-title media-card-title m-0">Segways</h4>
                  </div>
                </div></a>
              </div>

              <div class="media-platform-card"><a class="media-link" href="{% url 'media:walking_billboards_pdf' %}">
                <div class="card media-card media-card wow fadeInUp just">
                    <div class="row mx-auto p-2">
                      <img class="img-fluid mx-auto media-card-img z-depth-0" src="../../static/media/images/main-icons/100x100/WB.jpg" alt="Walking Billboards">
                    </div>
                    <div class="py-1 px-2 text-center">
                      <h4 class="card-title media-card-title m-0">Walking Billboards</h4>
                    </div>
                </div></a>
              </div>
          </div>

      </section>
  </div>
</div>

{% endblock %}